# Generated by Django 4.2.6 on 2023-10-22 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('biography', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bios', to='users.user')),
            ],
        ),
    ]
