# Generated by Django 4.2.6 on 2023-10-22 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='users.user')),
                ('blocker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='users.user')),
            ],
        ),
    ]
